apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sock-shop-rules
  namespace: monitoring
spec:
  groups:
  - name: sock-shop
    rules:
    - alert: PodFrequentRestart
      expr: increase(kube_pod_container_status_restarts_total[10m]) > 3
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod {{ $labels.pod }} has restarted frequently"
