prometheus:
  prometheusSpec:
    image:
      registry: crpi-ylw7gpcmxpqjz8c6.cn-wulanchabu.personal.cr.aliyuncs.com
      repository: yechen/prometheus
      tag: v3.10.0
    imagePullSecrets:
      - name: regcred
    retention: 2d  
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    image:
      registry: crpi-ylw7gpcmxpqjz8c6.cn-wulanchabu.personal.cr.aliyuncs.com
      repository: yqchen/alertmanager
      tag: v0.31.1
    imagePullSecrets:
      - name: regcred
  resources:
    requests:
      memory: 128Mi
      cpu: 50m

grafana:
  sidecar:
    datasources:
      enabled: false
  enabled: true
  image:
    registry: crpi-ylw7gpcmxpqjz8c6.cn-wulanchabu.personal.cr.aliyuncs.com
    repository: yqchen/grafana
    tag: 12.4.0
  imagePullSecrets:
    - name: regcred
  adminPassword: "admin"  
  service:
    type: NodePort
    nodePort: 30300
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated:9090
        access: proxy
        isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      sock-shop:
        gnetId: 11074  
        revision: 1
        datasource: Prometheus
