prometheus:
  service:
    type: NodePort  
  prometheusSpec:
    retention: 2d  # 保留时间
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi


alertmanager:
  enabled: true
  config:
    global:
      # 这里不需要 dingtalk 字段
    route:
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'dingtalk'
    receivers:
    - name: 'dingtalk'
      webhook_configs:
      - url: 'https://oapi.dingtalk.com/robot/send?access_token=6c68f322d0227254726a5229ec4975086a28087f8991ad39f9ddeb6944d9abf9&sign=SEC15cb5112a8a1b7fe84980e4c7296ae0ca9e9c6197fee4e139c0920615865c942'
        send_resolved: true
    templates:
    - '/etc/alertmanager/config/*.tmpl'
  service:
    type: NodePort
  resources:
    requests:
      memory: 128Mi
      cpu: 50m

grafana:
  sidecar:
    datasources:
      enabled: false  #需要禁用sidecar
  enabled: true
  adminPassword: "admin"  # 修改为你自己的密码
  service:
    type: NodePort
    nodePort: 30300
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated:9090
        access: proxy
        isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      # 导入一些预定义的 dashboard（可选）
      sock-shop:
        gnetId: 11074  # 这是 Sock Shop 的一个监控 dashboard id，可以搜索替换
        revision: 1
        datasource: Prometheus
