apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: session-db-redis-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:  
      app: session-db-redis-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - monitoring
