apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: node
    rules:
    - alert: NodeStatus
      expr: kube_node_status_condition{condition="Ready", status="true"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: " {{ $labels.node }}节点挂了"
        description: "{{ $labels.node }}节点挂了"
    - alert: NodeBytes
      expr: (1 - node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 > 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: " 磁盘使用率超过90% "
        description: " 磁盘使用率为$value "
