apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: RabbitMQQueueBacklog
      expr: increase(rabbitmq_queue_messages_ready{queue="shipping-task"}[5m]) > 100
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "队列 shipping-task 消息堆积 > 1000"
        description: "当前堆积 {{ $value }} 条消息"

    - alert: RabbitMQNoConsumer
      expr: rabbitmq_queue_consumers{queue="shipping-task"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "队列 shipping-task 无消费者"
        description: "队列消息将无法被消费"
